package com.song.filetransfer.model;


public class Constants {

    public final static String ACTION_DISPLAY_USER_IN = "ACTION_DISPLAY_USER_IN";
    public final static String ACTION_DISPLAY_USER_OFF = "ACTION_DISPLAY_USER_OFF";
    public final static String ACTION_DISPLAY_USER_FRIEND_REQUEST = "ACTION_DISPLAY_USER_FRIEND_REQUEST";
    public final static String ACTION_DISPLAY_USER_FILE_REQUEST = "ACTION_DISPLAY_USER_FILE_REQUEST";
    public final static String ACTION_DISPLAY_CONNECTION_CHANGE = "ACTION_DISPLAY_CONNECTION_CHANGE";
    public final static String ACTION_DISPLAY_FILE_LIST_CHANGE = "ACTION_DISPLAY_USER_FILE_LIST__CHANGE";
    public static final String ACTION_DISPLAY_FILE_STATE_CHANGE = "ACTION_DISPLAY_FILE_STATE_CHANGE";
    public static final String ACTION_DISPLAY_RECORD_LIST_CHANGE = "ACTION_DISPLAY_RECORD_LIST_CHANGE";
}
